name: Waypoints.Plates
version: 2.4
main: waypoints.plates.WpsPlatesPlugin
commands:
  wpssigns:
    description: root command
    usage: /<command> [subcommand] [args]
  waypointssigns:
    description: root command
    usage: /<command> [subcommand] [args]
depend: [Waypoints]